#!/bin/sh
set -eu

if [ "${SYNON_HOST_GITHUB_FIXTURE_MODE:-gh}" != "git" ]; then
  exit 1
fi
if [ "${1-} ${2-} ${3-} ${4-}" != "-c credential.interactive=never credential fill" ]; then
  printf '%s\n' "unexpected git arguments: $*" >&2
  exit 64
fi
input=$(cat)
case "$input" in
  *"protocol=https"*"host=github.com"*)
    printf '%s\n' 'protocol=https' 'host=github.com' 'username=git-user' 'password=github_pat_1234567890ABCDEFGHIJKL'
    ;;
  *)
    printf '%s\n' 'unexpected git credential input' >&2
    exit 64
    ;;
esac
