changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Highlights / 亮点
      labels:
        - enhancement
    - title: Fixes / 修复
      labels:
        - bug
    - title: Documentation / 文档
      labels:
        - documentation
    - title: Dependencies / 依赖
      labels:
        - dependencies
    - title: Other changes / 其他变更
      labels:
        - "*"
