#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
ROOT_DIR=$(cd "$SCRIPT_DIR/.." && pwd)
BIN="${1:-$ROOT_DIR/dist/synon-go}"

export SYNON_GOAL_STRICT="${SYNON_GOAL_STRICT:-1}"
export SYNON_GOAL_ALLOWED_PARTIAL="${SYNON_GOAL_ALLOWED_PARTIAL:-synon-link-im}"

export SYNON_RUNNER_ENABLED="${SYNON_RUNNER_ENABLED:-true}"
export SYNON_RUNNER_PROVIDER="${SYNON_RUNNER_PROVIDER:-openai_chat}"
export SYNON_RUNNER_CHAT_ENDPOINT="${SYNON_RUNNER_CHAT_ENDPOINT:-http://127.0.0.1:9/v1/chat/completions}"
export SYNON_RUNNER_CHAT_MODEL="${SYNON_RUNNER_CHAT_MODEL:-synon-go-smoke-model}"
export SYNON_RUNNER_CHAT_API_KEY="${SYNON_RUNNER_CHAT_API_KEY:-synon-go-smoke-key}"
export SYNON_RUNNER_CHAT_TOOLS="${SYNON_RUNNER_CHAT_TOOLS:-Read,ToolSearch,AgentRuntimeDoctor}"

export SYNON_COMPACT_SUMMARIZER_ENDPOINT="${SYNON_COMPACT_SUMMARIZER_ENDPOINT:-$SYNON_RUNNER_CHAT_ENDPOINT}"
export SYNON_COMPACT_SUMMARIZER_MODEL="${SYNON_COMPACT_SUMMARIZER_MODEL:-synon-go-compact-smoke-model}"
export SYNON_COMPACT_SUMMARIZER_API_KEY="${SYNON_COMPACT_SUMMARIZER_API_KEY:-$SYNON_RUNNER_CHAT_API_KEY}"

exec bash "$SCRIPT_DIR/goal-run.sh" "$BIN"
