package memorypolicy

import (
	"strings"
	"time"
	"unicode/utf16"
)

// Defaults and limits shared by the workspace memory pipeline. Changes to
// these values require behavioral tests for extraction, recall, and persistence.
const (
	EnabledDefault               = false
	PIClassifierEnabledDefault   = true
	ExtractEnabledDefault        = true
	ExtractModeDefault           = "forked"
	ExtractEveryNDefault         = 1
	ExtractMaxPerRun             = 5
	ExtractDeltaDefault          = true
	ContextInSystemPromptDefault = true
	ListingMaxEntities           = 40
	ProfileMaxRows               = 40
	FrameMaxRows                 = 20
	RecallRRFThreshold           = 0.029
	RecallInjectMax              = 6
	RecallProjectBoost           = 1.5
	RecallCrossProjectRankMax    = 3
	RecallCrossProjectMax        = 2
	RecallProfileMax             = 2
	RecallReserveMax             = 2
	RecallSpawnQueryMaxTokens    = 25
	RecallSpawnQueryDFMaxRatio   = 0.16
	SearchToolMax                = 20
	SearchToolRRFThreshold       = 0.0
	ReadToolMax                  = 100
	DedupWarnThreshold           = 0.025
	StaleAgeDays                 = 14
	StaleRankDecay               = 1.0

	// Shared search index, formatted bundle lines 58447-58530.
	SearchQueryMaxUTF16Units = 16384 // uJO
	RecallMinWords           = 3     // skills.search_min_words
	BM25K1                   = 1.2   // mJO
	BM25B                    = 0.75  // cJO
	RRFConstant              = 60.0  // pJO
	IndexBodyPreviewMax      = 120

	// Public API and memory tool schemas, formatted bundle lines 63069 and
	// 79555-79810.
	OperationsPerKindMax = 20
	TextMaxUTF16Units    = 1000
	CategoryMax          = 10
	CategoryNameMax      = 64
	CategoryGuidanceMax  = 280
	RelatedPriorRowsMax  = 3
	RemoveRetryAttempts  = 2

	// Rendering and staleness contracts, formatted bundle lines 73048-73110.
	ProfileBodyPreviewMax  = 300
	ListingBodyPreviewMax  = 60
	SearchBodyPreviewMax   = 200
	SearchExtraEntitiesMax = 3
	StalenessIDPrefixMax   = 8
	RelativeAgeDayCutoff   = 14

	// Prompt-injection gate, formatted bundle lines 77861-77990.
	PIClassifierConcurrency = 8 // LEO
	PIClassifierMaxTokens   = 512
	PIClassifierBusyRetries = 2
	StaticDecodeMaxPasses   = 1024

	// Extraction, formatted bundle lines 81520-81920.
	ExtractionTranscriptMaxUTF16Units = 8000
	ExtractionMaxTokens               = 2048
	ExtractionForkedTokenHeadroom     = 8192
	ExtractionForkedMaxTokens         = ExtractionMaxTokens + ExtractionForkedTokenHeadroom
	LiteralRepairMaxTokens            = 400
	LiteralRepairAttempts             = 2
	LiteralRepairPromptHeadroom       = 50

	// Persistent schema, formatted bundle line 3681. IDs generated by the
	// memory repositories are "mem_"/"memcat_" plus 12 UUID hex characters.
	GeneratedIDHexLength = 12
	MemoryIDMaxLength    = 36
	CategoryIDMaxLength  = 36
	ProjectIDMaxLength   = 255
	UserIDMaxLength      = 255
	ArtifactIDMaxLength  = 36
	VersionIDMaxLength   = 36
	FrameIDMaxLength     = 36
)

const PIClassifierDeadline = 30 * time.Second // QEO=30000
const ExtractionDeadline = 10 * time.Minute   // U0=600000

// UTF16Length matches JavaScript String.length, which is what the reference runtime's
// Zod maxLength checks and direct .length comparisons use.
func UTF16Length(value string) int {
	length := 0
	for _, r := range value {
		units := utf16.RuneLen(r)
		if units < 0 {
			units = 1
		}
		length += units
	}
	return length
}

// PrefixUTF16 applies the reference UTF-16-unit limit without creating an invalid
// Go string when the boundary falls between a surrogate pair.
func PrefixUTF16(value string, maxUnits int) string {
	if maxUnits <= 0 {
		return ""
	}
	if UTF16Length(value) <= maxUnits {
		return value
	}
	var out strings.Builder
	used := 0
	for _, r := range value {
		units := utf16.RuneLen(r)
		if units < 0 {
			units = 1
		}
		if used+units > maxUnits {
			break
		}
		out.WriteRune(r)
		used += units
	}
	return out.String()
}

func TruncateWithEllipsis(value string, maxUnits int) string {
	if UTF16Length(value) <= maxUnits {
		return value
	}
	if maxUnits <= 1 {
		return "…"
	}
	return PrefixUTF16(value, maxUnits-1) + "…"
}
