#!/usr/bin/env bash
set -Eeuo pipefail

ROOT="${SYNON_SOURCE_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
GO_BIN="${GO:-go}"
command -v "$GO_BIN" >/dev/null 2>&1 || {
  echo "[source-backend] Go 1.26 or newer is required; executable not found: $GO_BIN" >&2
  exit 1
}
GO_VERSION=$("$GO_BIN" env GOVERSION 2>/dev/null) || {
  echo "[source-backend] unable to read Go version from: $GO_BIN" >&2
  exit 1
}
if [[ ! "$GO_VERSION" =~ ^go1\.([0-9]+)(\.|$) ]] || (( 10#${BASH_REMATCH[1]:-0} < 26 )); then
  echo "[source-backend] Go 1.26 or newer is required; found: $GO_VERSION" >&2
  exit 1
fi
IFS=$'\t' read -r product_slug _ < <(cd "$ROOT" && env -u GOOS -u GOARCH "$GO_BIN" run -buildvcs=false ./scripts/product-identity)
if [[ -z "$product_slug" ]]; then
  echo "[source-backend] product identity did not provide a machine slug" >&2
  exit 1
fi
BUILD_DIR="${SYNON_DEV_BUILD_DIR:-${XDG_STATE_HOME:-$HOME/.local/state}/${product_slug}-dev}"
BINARY="$BUILD_DIR/synon-go"
CANDIDATE="$BUILD_DIR/synon-go.next"
LOCK_FILE="$BUILD_DIR/backend-watch.lock"
HOST_PID_FILE="$BUILD_DIR/backend-watch.pid"
ACCEPTED_MIGRATION_DIGEST_FILE="$BUILD_DIR/accepted-migration-digest"
PENDING_MIGRATION_DIGEST_FILE="$BUILD_DIR/pending-migration-digest"
POLL_SECONDS="${SYNON_DEV_POLL_SECONDS:-1}"
BUILD_RETRY_MIN_SECONDS="${SYNON_DEV_BUILD_RETRY_MIN_SECONDS:-5}"
BUILD_RETRY_MAX_SECONDS="${SYNON_DEV_BUILD_RETRY_MAX_SECONDS:-60}"
CHILD_PID=""

if ! [[ "$BUILD_RETRY_MIN_SECONDS" =~ ^[1-9][0-9]*$ ]] ||
  ! [[ "$BUILD_RETRY_MAX_SECONDS" =~ ^[1-9][0-9]*$ ]] ||
  (( BUILD_RETRY_MIN_SECONDS > BUILD_RETRY_MAX_SECONDS )); then
  echo "[source-backend] build retry bounds must be positive integers with min <= max" >&2
  exit 64
fi

mkdir -p "$BUILD_DIR"
command -v flock >/dev/null 2>&1 || {
  echo "[source-backend] required command not found: flock" >&2
  exit 1
}
exec {LOCK_FD}>"$LOCK_FILE"
if ! flock -n "$LOCK_FD"; then
  existing_pid="unknown"
  if [[ -f "$HOST_PID_FILE" ]]; then
    existing_pid=$(tr -d '\r\n' <"$HOST_PID_FILE")
  fi
  echo "[source-backend] another watcher already owns this build directory (pid=$existing_pid)" >&2
  exit 73
fi

atomic_write() {
  local destination="$1"
  local value="$2"
  local temporary="$destination.tmp.$$"
  printf '%s\n' "$value" >"$temporary"
  mv -f "$temporary" "$destination"
}

remove_owned_pid_file() {
  local observed=""
  if [[ -f "$HOST_PID_FILE" ]]; then
    observed=$(tr -d '\r\n' <"$HOST_PID_FILE")
  fi
  if [[ "$observed" == "$$" ]]; then
    rm -f "$HOST_PID_FILE"
  fi
}

atomic_write "$HOST_PID_FILE" "$$"

source_digest() {
  (
    cd "$ROOT"
    # Only backend build/runtime inputs belong in this digest.  Frontend host
    # supervision lives under scripts/dev as well; including that directory
    # made an unrelated frontend-host edit rebuild and restart the live API.
    # Python bytecode caches (__pycache__/*.pyc) are regenerated by bundled
    # MCP servers on every tool call. Including them in the digest made each
    # MCP invocation look like a source edit and restart the live API, which
    # interrupted in-flight tasks.
    find cmd internal assets skills -type f \
      -not -path '*/__pycache__/*' -not -path '*/testdata/*' \
      -not -name '*.pyc' -not -name '*_test.go' \
      -printf '%T@ %s %p\n'
    find . -maxdepth 1 -type f \
      \( -name 'go.mod' -o -name 'go.sum' -o -name '*.go' \) \
      -printf '%T@ %s %p\n'
  ) | LC_ALL=C sort | sha256sum | cut -d' ' -f1
}

migration_digest() {
	(
		cd "$ROOT"
		find internal/persistence/workspace -maxdepth 1 -type f \
			\( -name 'versioned_schema.go' -o -name 'schema_rescue_v21.go' -o \
			-name '*schema_migration*.go' -o -name 'schema_migration_*.go' \) \
			-not -name '*_test.go' \
			-printf '%p\n' 2>/dev/null |
			LC_ALL=C sort |
			while IFS= read -r path; do
				printf '%s\0' "$path"
				sha256sum "$path" | cut -d' ' -f1
			done
	) | sha256sum | cut -d' ' -f1
}

accepted_migration_digest() {
	[[ -f "$ACCEPTED_MIGRATION_DIGEST_FILE" ]] || return 1
	tr -d '\r\n' <"$ACCEPTED_MIGRATION_DIGEST_FILE"
}

migration_inputs_are_accepted() {
	local current accepted
	current="$(migration_digest)"
	if ! accepted="$(accepted_migration_digest)"; then
		if [[ -x "$BINARY" ]]; then
			atomic_write "$PENDING_MIGRATION_DIGEST_FILE" "$current"
			return 1
		fi
		return 0
	fi
	if [[ "$current" != "$accepted" ]]; then
		atomic_write "$PENDING_MIGRATION_DIGEST_FILE" "$current"
		return 1
	fi
	rm -f "$PENDING_MIGRATION_DIGEST_FILE"
	return 0
}

stop_child() {
  if [[ -z "$CHILD_PID" ]] || ! kill -0 "$CHILD_PID" 2>/dev/null; then
    CHILD_PID=""
    return
  fi
  kill -TERM "$CHILD_PID" 2>/dev/null || true
  for _ in $(seq 1 50); do
    if ! kill -0 "$CHILD_PID" 2>/dev/null; then
      wait "$CHILD_PID" 2>/dev/null || true
      CHILD_PID=""
      return
    fi
    sleep 0.1
  done
  kill -KILL "$CHILD_PID" 2>/dev/null || true
  wait "$CHILD_PID" 2>/dev/null || true
  CHILD_PID=""
}

runtime_health_json() {
  if [[ -n "${SYNON_DEV_RUNTIME_HEALTH_FILE:-}" ]]; then
    [[ -f "$SYNON_DEV_RUNTIME_HEALTH_FILE" ]] || return 1
    cat "$SYNON_DEV_RUNTIME_HEALTH_FILE"
    return 0
  fi
  command -v curl >/dev/null 2>&1 || return 1
  # A degraded backend intentionally answers /health with a non-2xx status but
  # still returns the authoritative runtime counters needed for a safe idle
  # activation.  Treat transport failure as unavailable, while preserving any
  # well-formed health body for the fail-closed parser below.
  curl --silent --show-error --max-time 1 http://127.0.0.1:8766/health 2>/dev/null
}

activate_candidate_if_idle() {
  local health active draining
  if [[ -z "$CHILD_PID" ]] || ! kill -0 "$CHILD_PID" 2>/dev/null; then
    CHILD_PID=""
    return 0
  fi
  health="$(runtime_health_json)" || return 1
  if [[ "$health" =~ \"active_session_runs\":[[:space:]]*([0-9]+) ]]; then
    active="${BASH_REMATCH[1]}"
  else
    return 1
  fi
  if [[ "$health" =~ \"runtime_draining\":[[:space:]]*(true|false) ]]; then
    draining="${BASH_REMATCH[1]}"
  else
    return 1
  fi
  if (( active != 0 )) || [[ "$draining" == "true" ]]; then
    return 1
  fi

  # SIGUSR1 asks the backend to atomically enter draining mode only if no
  # runner is active. A task admitted between the health probe and this signal
  # makes the backend refuse the reload, closing the last check/stop race.
  kill -USR1 "$CHILD_PID" 2>/dev/null || return 1
  for _ in $(seq 1 50); do
    if ! kill -0 "$CHILD_PID" 2>/dev/null; then
      wait "$CHILD_PID" 2>/dev/null || true
      CHILD_PID=""
      return 0
    fi
    health="$(runtime_health_json)" || {
      sleep 0.1
      continue
    }
    if [[ "$health" =~ \"runtime_draining\":[[:space:]]*true ]]; then
      sleep 0.1
      continue
    fi
    # The idle-drain request lost a race with a newly admitted task. Keep the
    # verified current backend live and retry activation after that task ends.
    return 1
  done
  health="$(runtime_health_json)" || health=""
  if [[ "$health" =~ \"runtime_draining\":[[:space:]]*true ]]; then
    stop_child
    return 0
  fi
  return 1
}

cleanup() {
  stop_child
  rm -f "$CANDIDATE"
  remove_owned_pid_file
}

shutdown() {
  trap - EXIT INT TERM
  cleanup
  exit 0
}

trap cleanup EXIT
trap shutdown INT TERM

build_candidate() {
  local expected_digest="$1"
  local observed_digest=""
  echo "[source-backend] building from $ROOT"
  rm -f "$CANDIDATE"
  if ! (cd "$ROOT" && "$GO_BIN" build -buildvcs=false -o "$CANDIDATE" ./cmd/synon); then
    rm -f "$CANDIDATE"
    echo "[source-backend] build failed; the previous backend remains active" >&2
    return 1
  fi
  observed_digest="$(source_digest)"
  if [[ "$observed_digest" != "$expected_digest" ]]; then
    rm -f "$CANDIDATE"
    echo "[source-backend] source changed during build; discarding the unstable candidate" >&2
    return 75
  fi
  chmod 0755 "$CANDIDATE"
  if ! "$CANDIDATE" assets verify --root "$ROOT" >/dev/null; then
    rm -f "$CANDIDATE"
    echo "[source-backend] candidate asset verification failed; the previous backend remains active" >&2
    return 1
  fi
  mv -f "$CANDIDATE" "$BINARY"
}

start_candidate() {
	local source_skill_dirs="${SYNON_SKILL_DIRS:-}"
	local model_env="/home/victor_1/.config/synon-go/workbench-model.env"
	if [[ -f "$model_env" ]]; then
		set -a; source "$model_env"; set +a
	fi
	if [[ -d "$ROOT/skills" ]]; then
		if [[ -n "$source_skill_dirs" ]]; then
			source_skill_dirs="$ROOT/skills,$source_skill_dirs"
		else
			source_skill_dirs="$ROOT/skills"
		fi
	fi
  echo "[source-backend] starting $BINARY serve"
  (cd "$ROOT" && SYNON_SKILL_DIRS="$source_skill_dirs" exec "$BINARY" serve) &
  CHILD_PID=$!
}

last_successful_digest=""
failed_digest=""
blocked_migration_digest=""
pending_activation_digest=""
reported_deferred_activation_digest=""
next_retry_epoch=0
retry_delay="$BUILD_RETRY_MIN_SECONDS"
initial_digest="$(source_digest)"
if ! migration_inputs_are_accepted; then
	if [[ ! -x "$BINARY" ]]; then
		echo "[source-backend] migration inputs are not accepted and no verified backend is available" >&2
		exit 1
	fi
	blocked_migration_digest="$(<"$PENDING_MIGRATION_DIGEST_FILE")"
	echo "[source-backend] migration inputs changed; keeping the accepted backend until digest $blocked_migration_digest is explicitly verified" >&2
	# The accepted binary did not come from initial_digest. Keep the source
	# digest unacknowledged so accepting the pending migration after a service
	# restart resumes the candidate build instead of leaving the old binary live.
elif build_candidate "$initial_digest"; then
	last_successful_digest="$initial_digest"
	if [[ ! -f "$ACCEPTED_MIGRATION_DIGEST_FILE" ]]; then
		atomic_write "$ACCEPTED_MIGRATION_DIGEST_FILE" "$(migration_digest)"
	fi
else
  initial_build_status=$?
  if [[ ! -x "$BINARY" ]]; then
    echo "[source-backend] no previous successful build is available" >&2
    exit 1
  fi
  echo "[source-backend] starting the previous successful build" >&2
  if (( initial_build_status != 75 )); then
    failed_digest="$initial_digest"
    next_retry_epoch=$(( $(date +%s) + retry_delay ))
    retry_delay=$(( retry_delay * 2 ))
    if (( retry_delay > BUILD_RETRY_MAX_SECONDS )); then
      retry_delay="$BUILD_RETRY_MAX_SECONDS"
    fi
  fi
fi
start_candidate

while true; do
  sleep "$POLL_SECONDS"
	current_digest="$(source_digest)"
	if [[ "$current_digest" != "$last_successful_digest" ]]; then
		if ! migration_inputs_are_accepted; then
			current_migration_digest="$(<"$PENDING_MIGRATION_DIGEST_FILE")"
			if [[ "$current_migration_digest" != "$blocked_migration_digest" ]]; then
				blocked_migration_digest="$current_migration_digest"
				echo "[source-backend] migration inputs changed; keeping the accepted backend until digest $blocked_migration_digest is explicitly verified" >&2
			fi
			continue
		fi
		blocked_migration_digest=""
		if [[ "$current_digest" != "$failed_digest" ]]; then
      # Debounce editors that update a file through multiple rename/write steps.
      sleep 0.35
      current_digest="$(source_digest)"
      failed_digest=""
      next_retry_epoch=0
      retry_delay="$BUILD_RETRY_MIN_SECONDS"
    fi
    now_epoch="$(date +%s)"
    if (( now_epoch >= next_retry_epoch )); then
      if build_candidate "$current_digest"; then
        last_successful_digest="$current_digest"
        pending_activation_digest="$current_digest"
        failed_digest=""
        next_retry_epoch=0
        retry_delay="$BUILD_RETRY_MIN_SECONDS"
      else
        build_status=$?
        if (( build_status == 75 )); then
          failed_digest=""
          next_retry_epoch=0
        else
          failed_digest="$current_digest"
          next_retry_epoch=$(( now_epoch + retry_delay ))
          echo "[source-backend] retrying failed digest in ${retry_delay}s" >&2
          retry_delay=$(( retry_delay * 2 ))
          if (( retry_delay > BUILD_RETRY_MAX_SECONDS )); then
            retry_delay="$BUILD_RETRY_MAX_SECONDS"
          fi
        fi
      fi
    fi
  fi
  if [[ -n "$pending_activation_digest" && "$current_digest" == "$pending_activation_digest" ]]; then
    if activate_candidate_if_idle; then
      start_candidate
      echo "[source-backend] source update is live"
      pending_activation_digest=""
      reported_deferred_activation_digest=""
    elif [[ "$reported_deferred_activation_digest" != "$pending_activation_digest" ]]; then
      echo "[source-backend] verified update built; activation deferred until active tasks finish"
      reported_deferred_activation_digest="$pending_activation_digest"
    fi
  elif [[ -n "$CHILD_PID" ]] && ! kill -0 "$CHILD_PID" 2>/dev/null; then
    wait "$CHILD_PID" 2>/dev/null || true
    CHILD_PID=""
    echo "[source-backend] backend exited; restarting the last successful build" >&2
    start_candidate
    pending_activation_digest=""
    reported_deferred_activation_digest=""
  fi
done
